### ISSUE TITLE
Support for swift 3.0

### ISSUE THREAD

**Issue by paresh-navadiya** [gokulgovind/GLNotificationBar#1]
Thanks for wonderful library

My concern was is there any support for swift 3.0 because its has become compulsory to update to swift 3.0 in coming days.

**Comment by zammitjames** [comment]
Yep, was about to open the same issue! Swift 3 is a must unfortunately, and this library seems too awesome to miss out on!

**Comment by gokulgovind** [comment]
Sure guys ASAP it'll will be updated with **Swift 3**.

**Comment by zammitjames** [comment]
@paresh-navadiya  @gokulgovind forked and updated the main GLNotificationBar.swift to SWIFT 3, feel free to take it from here: https://github.com/zammitjames/GLNotificationBar/tree/master/GLNotificationBar

**Comment by gokulgovind** [comment]
@zammitjames thank you :) , will be updated soon.

**Comment by zammitjames** [comment]
@gokulgovind no prob! Great library :)

**Comment by Rashesh-Bosamiya** [comment]
why notification `title` and `body` coming as `Optional("some text")`?

**Comment by gokulgovind** [comment]
@Rashesh-Bosamiya those strings may be unwrapped, will be addressed soon.

**Comment by Rashesh-Bosamiya** [comment]
Means, are you gonna upload new version for this library?

**Comment by pprevalon** [comment]
@Rashesh-Bosamiya  did you find any solutions to the the optional tile and body

**Comment by gokulgovind** [comment]
@pprevalon  Check CalebeNP's comment on **Closed issue**,

to "fix" this you just have to make this change:

**Before:** fileprivate func setUpNotificationBar(_ header:String!, body:String!, notificationStyle:GLNotificationStyle)
**After:** fileprivate func setUpNotificationBar(_ header:String, body:String, notificationStyle:GLNotificationStyle)
