### ISSUE TITLE
Apple style, including shadow

### ISSUE THREAD

**Issue by CavalcanteLeo** [gokulgovind/GLNotificationBar#14]
I've seen some layout differences between apple style and GLNotificationBar.

Mostly is because of the missing shadow, where it doesn't show legible the notificationBar.

I've changed to the apple's look and feel, but for that, i needed to remove the UIVisualEffect.
On the screenshot, the layout seems a bit different yet, like spaces, sizes and even bg colors, but it's only to show how it works with shadow.

I can submit a PR for that, but remember, it doesn't work well with UIVisualEffect

![styles](https://user-images.githubusercontent.com/1735944/28790698-7d2b8d88-7600-11e7-93cc-6bc0ce7fec45.jpg)

Shall i go further and change all look and feel to look exactly the same as apple, or leave like that?
The bad thing is that the current banner is not readable with white layouts like mine.

You can try the diference using here:
```
pod 'GLNotificationBar', :git => 'git@github.com:CavalcanteLeo/GLNotificationBar.git', :branch => 'shadow'
```
and include `setShadow true` on the project

**Comment by CavalcanteLeo** [comment]
Here's how it looks with all colors variants 

![3ed33ad4-562c-454c-80ac-ce993bd294d9](https://user-images.githubusercontent.com/1735944/28793110-54b2c0f8-7608-11e7-922c-1d383c2380ae.PNG)
![2683a0d1-63d4-4a35-9890-58633ca288f1](https://user-images.githubusercontent.com/1735944/28793112-57098008-7608-11e7-8c88-9006c0add63c.PNG)

**Comment by gokulgovind** [comment]
@CavalcanteLeo thanks for your initiative.

For now let it be like this ,Is that possible to add shadow to visual effect view ?. If so, no need to do major changes right.

**Comment by CavalcanteLeo** [comment]
Its not possible to add shadows on visual effect, i added a transparent uiview behind, and when active the shadow, i change the color to white

In fact, you can add shadow to UIVisualEffect, but as the view is half transparent, the shadow will appear inside too, looking terrible

**Comment by CavalcanteLeo** [comment]
https://github.com/gokulgovind/GLNotificationBar/pull/15

**Comment by CavalcanteLeo** [comment]
Any news about it?

it's quite ugly and ineligible without shadow

**Comment by azhararmar** [comment]
Agreed, It would be nice to have the shadow. It looks odd without the shadow.

**Comment by gokulgovind** [comment]
Hi @CavalcanteLeo ,

Nice to see you back, Sorry for the delay actually i was busy with my work. Now i have merged your pull request. Please check it. 

Nice work work 👍 , Thank for your PR. :)

Soon i'll push next version with other issues fixed.

Thanks

**Comment by CavalcanteLeo** [comment]
great, thank you, dude!
