### ISSUE TITLE
Always show the keyboard

### ISSUE THREAD

**Issue by azhararmar** [gokulgovind/GLNotificationBar#17]
When a notification is displayed, keyboard is hidden. I don't want this behavior. Can you point me where in the file I need to change to make this happen?

**Comment by gokulgovind** [comment]
Hi @azhararmar ,

Just add below lines to last of this `func setUpDetailedNotificationBar(_ header: String!, body: String!, action: [GLNotifyAction]!)` function (Some where around line:533)

   `let action = actionArray[2]
    self.setUpTextField(action,senderTag:2)`

If everything added as explained, `TextField` will be displayed when you open an notification by swiping down.

By believing this would help you, closing this issue now. Feel free to reopen if needed. 

Thanks.
