### ISSUE TITLE
Title & Detail Text are coming up as Optional("some text")

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [gokulgovind/GLNotificationBar#2]
Optional("Some text")

Output coming as above, Although I am passing simple unwrapped string.

In Swift 3.

I have downloaded from this URL: https://github.com/zammitjames/GLNotificationBar

**Comment by CalebeNP** [comment]
@Rashesh-Bosamiya to "fix" this you just have to make this change:

**Before:** `fileprivate func setUpNotificationBar(_ header:String!, body:String!, notificationStyle:GLNotificationStyle)`
**After:** `fileprivate func setUpNotificationBar(_ header:String, body:String, notificationStyle:GLNotificationStyle)`

**Comment by Rashesh-Bosamiya** [comment]
Many thanks!

Got my problem solved!
