### ISSUE TITLE
setColorStyle

### ISSUE THREAD

**Issue by fadizant** [gokulgovind/GLNotificationBar#20]
setColorStyle dose not exist ?

**Comment by gokulgovind** [comment]
Hi @fadizant ,

No changes made on `setColorStyle`, you can still make use of it. For your reference please check **Line:208** in `GLNotificationBar.swift`

Thanks.

**Comment by gokulgovind** [comment]
HI @fadizant ,

For now I'm closing the issue. Feel free to reopen if you have any more queries.

Thanks.
