### ISSUE TITLE
Bar title and message printing as optional

### ISSUE THREAD

**Issue by pprevalon** [gokulgovind/GLNotificationBar#5]
- title and message is printing as an optional
- message is printing as "Yesterday is today\'s memory, and tomorrow is today\'s dream"

let notificationBar = GLNotificationBar(title: "Today Quote", message: "Yesterday is today's memory, and tomorrow is today's dream.", preferredStyle: .detailedBanner, handler: nil)

            notificationBar.addAction(GLNotifyAction(title: "Like", style: .default, handler: { (action) in
                print("I Like this quote")
            }))
            notificationBar.addAction(GLNotifyAction(title: "Cancel", style: .cancel, handler: nil))

**Comment by gokulgovind** [comment]
@pprevalon Check CalebeNP's comment on Closed issue,

to "fix" this you just have to make this change:

Before: fileprivate func setUpNotificationBar(_ header:String!, body:String!, notificationStyle:GLNotificationStyle)
After: fileprivate func setUpNotificationBar(_ header:String, body:String, notificationStyle:GLNotificationStyle)
