### ISSUE TITLE
Crash : when continuously showing notification bar and tapping anyone of them

### ISSUE THREAD

**Issue by paresh-navadiya** [gokulgovind/GLNotificationBar#6]
[NotificationBar didSelectmessage:]: unrecognized selector sent to instance'

Can anyone provide solution?

**Comment by gokulgovind** [comment]
Hai @paresh-navadiya , sorry for late response.I had checked many times, Unable to reproduce the issue. Can you explain the exact scenario.

**Comment by rsimenok** [comment]
@gokulgovind 

If i set `handler` to nil i get crash, try it.
`[[GLNotificationBar alloc] initWithTitle:@"test" message:@"test" preferredStyle:0 handler:nil];`

line 666 in GLNotificationBar.swift

`messageDidSelect(true)`

should be
```
if messageDidSelect != nil {
     messageDidSelect(true)
}
```

**Comment by gokulgovind** [comment]
@rsimenok thanks for the issue, sure it will b fixed soon :)

**Comment by rsimenok** [comment]
@gokulgovind Hello, how soon it will be fixed? Thank you :)

**Comment by CavalcanteLeo** [comment]
I've fixed it, it's in my changes of the shadow support, but still doing it, i will send a PR soon
You can try it using:

`pod 'GLNotificationBar', :git => 'git@github.com:CavalcanteLeo/GLNotificationBar.git', :branch => 'shadow'`

**Comment by CavalcanteLeo** [comment]
fixed here: https://github.com/gokulgovind/GLNotificationBar/pull/15/files#diff-140f46f2cc91d7b88e9b901ff9dd2061R112

**Comment by gokulgovind** [comment]
Hi @rsimenok , 

Pull request has been merged. Please make sure if the issue has been fixed.

If't feel free to reopen the bug.

Thanks.
