### ISSUE TITLE
Notification Bar Message Label multiline. Lengthen its height according to content.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [gokulgovind/GLNotificationBar#7]
The current problem is truncating trailing characters when content is bigger.

label height should grow.

Is there any solution?

**Comment by gokulgovind** [comment]
Yup, 
1. In `setUpNotificationBar` add `notificationBar.body.numberOfLines = 0`
2. And change Vertical VFL as 
`let vertical = NSLayoutConstraint.constraintsWithVisualFormat("V:|[view(>=barHeight)]", options: [], metrics: ["barHeight":BAR_HEIGHT], views: ["view":notificationBar])
        constraints += vertical`

**Comment by gokulgovind** [comment]
If you want notification bar to stop expanding at particular point, Just change number of lines **something not equal to 0**
`notificationBar.body.numberOfLines = 5`

**Comment by Rashesh-Bosamiya** [comment]
Ok, Let me check.

**Comment by Rashesh-Bosamiya** [comment]
Fine, This solution working.

Thank you very much. Appreciate.

Just wondering, Does it support `attributedString` ?

**Comment by gokulgovind** [comment]
Yes it does, but need to change some code.
1. Change init method as
`@objc public init(title:String!, message :NSMutableAttributedString!, preferredStyle:GLNotificationStyle, handler: ((Bool) -> Void)?) {`
2. And change `setUpNotificationBar` method as
`private func setUpNotificationBar(header:String, body:NSAttributedString, notificationStyle:GLNotificationStyle) {`
3. In `setUpNotificationBar` method change `notificationBar.body.text` as `notificationBar.body.attributedText`
4. And init notification bar as
`let notificationBar = GLNotificationBar(title: "", message: 'Pass you NSMutableAttributedString here', preferredStyle: .SimpleBanner, handler: nil)`
**NOTE:** `title` must be empty in this case.

**Comment by Rashesh-Bosamiya** [comment]
Thank you very much!!! :1st_place_medal:
